development:
  secret_token: "my_secret_token"
  secret_key_base: "sk_test_51OyMEzD1D5FoN2UgcT8xxzApj19HMVbOFJ4MXSY8G0O7psM90KF3Z1jdwgB7jmOF2pmx9SKb0TNpYsNiNqlhqdqV00xLnM4Fpg"

test:
  secret_token: "my_secret_token"
  secret_key_base: "sk_test_51OyMEzD1D5FoN2UgcT8xxzApj19HMVbOFJ4MXSY8G0O7psM90KF3Z1jdwgB7jmOF2pmx9SKb0TNpYsNiNqlhqdqV00xLnM4Fpg"